name: 'Organization workflow action'
description: 'Action to register organization workflow'
inputs:
  id: 
    description: 'id'
    required: true
  run_id: 
    description: 'run id'
    required: true
  name: 
    description: 'name'
    required: true
  callback_url: 
    description: 'callback url'
    required: true
  enforce: 
    description: 'enforce'
    required: false
    default: false
runs:
  using: "composite"
  steps: 
    - run: |
        curl -G \
          "${{ inputs.callback_url }}" \
          -d id=${{ inputs.id }} \
          -d run_id=${{ inputs.run_id }} \
          -d name=${{ inputs.name }} \
          -d enforce=${{ inputs.enforce }}
      shell: bash