name: Staging deploy

on:
  push:
    branches: [ main ]

env:
  CONTAINER_NAME: organization-workflows
  REPO: svanboxel/organization-workflows
  REGISTRY: ghcr.io/
  APP_NAME: organization-workflows-bot

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: | 
        npm ci
        npm run build --if-present
        npm test
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
    - name: Build  Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        load: true
        tags: |
          ${{ env.REGISTRY }}${{ env.REPO }}:${{ github.sha }}
          ${{ env.REGISTRY }}${{ env.REPO }}:latest
    - run: |
        docker push ${{ env.REGISTRY }}${{ env.REPO }}:${{ github.sha }}

  deploy:
    needs: [build-and-publish]
    if: github.ref == 'refs/heads/main'
    environment: 
      name: staging
      url: https://organization-workflows-bot-staging.azurewebsites.net
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.APP_NAME }}
        slot-name: staging
        images: ${{ env.REGISTRY }}${{ env.REPO }}:${{ github.sha }}
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_STAGING }}
    - uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.CI_TEST_TOKEN }}
        script: |
          core.info(`Running e2e test for staging environment`);
          const script = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/scripts/e2e-test.js`);
          await script(93678, "${{ env.TEST_ORG }}", {github, core});
