name: Production deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CONTAINER_NAME: organization-workflows
  REPO: svanboxel/organization-workflows
  REGISTRY: ghcr.io/
  APP_NAME: organization-workflows-bot

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: | 
        npm ci
        npm run build --if-present
        npm test
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
    - name: Build  Docker Image
      uses: docker/build-push-action@v2
      with:
        load: true
        tags: |
          ${{ env.REGISTRY }}${{ env.REPO }}:${{ github.sha }}
          ${{ env.REGISTRY }}${{ env.REPO }}:latest
    - run: |
        docker push ${{ env.REGISTRY }}${{ env.REPO }}:${{ github.sha }}

  deploy:
    needs: [build-and-publish]
    if: github.ref == 'refs/heads/main'
    environment: 
      name: production
      url: https://organization-workflows-bot.azurewebsites.net
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.APP_NAME }}
        slot-name: production
        images: ${{ env.REGISTRY }}${{ env.REPO }}:${{ github.sha }}
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_78bd60d0ca1e43dca5d19f76e28007bb }}

 