name: App Stats

on:
  workflow_dispatch:
  push:

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/app-stats-action@v1.x
        id: stats
        with:
          id: 93006
          private_key: ${{ secrets.APP_KEY_PROD }}
      - run: "echo installations: '${{ steps.stats.outputs.installations }}'"
      - run: "echo repositories: '${{ steps.stats.outputs.repositories }}'"
      - run: "echo suspended: '${{ steps.stats.outputs.suspended_installations }}'"
#     - run: "echo most popular repositories: '${{ steps.stats.outputs.popular_repositories }}'"
        
      - uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          source_dir: .
          container_name: stats
          connection_string: ${{ secrets.STATS_CONNECTION_STRING }}
